#!/bin/bash
password=$1
if [ -z "$password" ] 
then
	clear
	echo "Password to lookup:"
	read password
fi
filename="pwned.hash"

getHash(){
	hash=$(echo -n "$password" | libressl-openssl sha1)
	hash=${hash:9}
	range=${hash:0:5}
	remainder=${hash:6}
}

apiRequest(){
	results=$(curl -s https://api.pwnedpasswords.com/range/$range > $HOME/$filename && grep -i $remainder $HOME/$filename)
	noTimes="${results:36}"
	if [ -z "$results" ]
	then
		clear
		echo "You seem safe.... .... for now"
	else
		clear
		printf "Oof...!\nThe password you input has been leaked!\nTimes found: $noTimes\nYou might want to change that!"
	fi
}

clean(){
	rm $HOME/$filename
}
getHash
apiRequest
clean
