#!/bin/bash

LENGTH=$1
if [ -z $LENGTH ]
then
	LENGTH=40
fi
PASSWORD=$(openssl rand -base64 $LENGTH)
echo ${PASSWORD%??} | xclip -selection c
notify-send "Password Generator" "Password copied to clipboard."
echo "- Password copied to clipboard."
