#!/bin/sh
notify-send "Pomodoro started." "Work concentrated for 25 minutes."
message=$1
while true
do
	clear
	cowsay "${message:-25 minutes}"
	sleep 2
	notify-send "Issa time" "Get some rest"
	mpv --quiet $PWD/pomodoro.mp3
  clear
	cowsay "Take a break!"
	sleep 5m
	notify-send "Get to it!" "Time to work!"
	mpv --quiet $PWD/pomodoro.mp3
done
