#!/bin/sh
notify-send "Pomodoro started." "Work concentrated for 25 minutes."

while true
do
	clear
	cowsay "25 minutes"
	sleep 25m
	notify-send "Issa time" "Get some rest"
	mpv --quiet ~/bin/pomodoro.mp3
  clear
	cowsay "Take a break!"
	sleep 5m
	notify-send "Get to it!" "Time to work!"
	mpv --quiet ~/bin/pomodoro.mp3
done
